import { reactive } from 'vue'

// ── Base translation keys (all values for TR, used as template for others) ────
const BASE = {
  appName:                   '',
  login:                     '',
  register:                  '',
  logout:                    '',
  email:                     '',
  password:                  '',
  passwordConfirm:           '',
  fullName:                  '',
  submit:                    '',
  sending:                   '',
  loading:                   '',
  saving:                    '',
  cancel:                    '',
  back:                      '',
  newTicket:                 '',
  myTickets:                 '',
  ticketNo:                  '',
  category:                  '',
  subject:                   '',
  status:                    '',
  date:                      '',
  detail:                    '',
  ticketDetail:              '',
  timeline:                  '',
  updateStatus:              '',
  note:                      '',
  save:                      '',
  noTickets:                 '',
  titleLabel:                '',
  titlePlaceholder:          '',
  msgLabel:                  '',
  msgPlaceholder:            '',
  adminBadge:                '',
  created:                   '',
  statusChanged:             '',
  statusOpen:                '',
  statusInProgress:          '',
  statusClosed:              '',
  statusSubmitted:           '',
  statusReviewing:           '',
  statusWaitingDepartment:   '',
  statusAnswered:            '',
  cat0:                      '',
  cat1:                      '',
  cat2:                      '',
  cat3:                      '',
  cat4:                      '',
  cat5:                      '',
  adminHint:                 '',
  waiting:                   '',
  allRequests:               '',
  total:                     '',
  filterAll:                 '',
  welcomeBack:               '',
  loginDesc:                 '',
  noAccount:                 '',
  invalidCreds:              '',
  connError:                 '',
  Complaint:                 '',
  Suggestion:                '',
  SupportRequest:            '',
  Request:                   '',
  Appreciation:              '',
  Question:                  '',
  InfoRequest:               '',
  langTr:                    '',
  langEn:                    '',
  langZh:                    '',
  langAz:                    '',
  langRu:                    '',
  langKk:                    '',
  langAr:                    '',
  langEs:                    '',
  langDe:                    '',
  langJa:                    '',
  langUr:                    '',
  langKo:                    '',
  myTicketsSub:              '',
  searchPlaceholder:         '',
  chartCategory:             '',
  chartTrend:                '',
  chartDept:                 '',
  chartAging:                '',
  chartPerformance:          '',
  statRate:                  '',
  statUnansweredCount:       '',
  statResolved:              '',
  statPending:               '',
  statWaiting:               '',
  statUnanswered:            '',
  statTotal:                 '',
  filterMonth:               '',
  filterYear:                '',
  filterCustom:              '',
  apply:                     '',
  exportPdf:                 '',
  aging45:                   '',
  aging60:                   '',
  aging90:                   '',
  aging180:                  '',
  noDeptData:                '',
  pdfReportTitle:            '',
  pdfOfficialDoc:            '',
  pdfGeneratedBy:            '',
  pdfAllTime:                '',
  catInfo:                   '',
  catThanks:                 '',
  perfScore:                 '',
  perfOverdue:               '',
  perfCritical:              '',
  perfTransfer:              '',
  perfInProgress:            '',
  perfExcellent:             '',
  perfGood:                  '',
  perfWarning:               '',
  perfCriticalLabel:         '',
  perfResRate:               '',
  perfOverdueRate:           '',
  chartSatisfaction:         '',
  chartComplaint:            '',
  chartStaffType:            '',
  staffAcademic:             '',
  staffAdmin:                '',
  staffWorker:               '',
  staffStudent:              '',
  staffOther:                '',
  publicApply:               '',
  publicTrack:               '',
  publicTrackSub:            '',
  personalInfo:              '',
  firstName:                 '',
  lastName:                  '',
  idNumber:                  '',
  jobTitle:                  '',
  address:                   '',
  hideInfo:                  '',
  hideInfoSub:               '',
  required:                  '',
  optional:                  '',
  nextStep:                  '',
  prevStep:                  '',
  finishApply:               '',
  cancelApply:               '',
  termsTitle:                '',
  termsAccept:               '',
  summary:                   '',
  trackButton:               '',
  trackResult:               '',
  newQuery:                  '',
  noDeptAssigned:            '',
  timelineTitle:             '',
  trackDescription:          '',
  applySuccess:              '',
  trackingNo:                '',
  trackNow:                  '',
  relevantDept:              '',
  selectDept:                '',
  visitorAction:             '',
  newApplication:            '',
  trackApplication:          '',
  forgotPassword:            '',
  copyright:                 '',
}

// ── Dictionary ────────────────────────────────────────────────────────────────
export const dict = {
  // ─── Türkçe ──────────────────────────────────────────────────────────────
  tr: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'Giriş Yap',
    register:                 'Kayıt Ol',
    logout:                   'Çıkış',
    email:                    'E-posta',
    password:                 'Şifre',
    passwordConfirm:          'Şifre Tekrar',
    fullName:                 'Ad Soyad',
    submit:                   'Gönder',
    sending:                  'Gönderiliyor…',
    loading:                  'Yükleniyor…',
    saving:                   'Kaydediliyor…',
    cancel:                   'İptal',
    back:                     '← Geri',
    newTicket:                'Yeni Talep',
    myTickets:                'Taleplerim',
    ticketNo:                 'Başvuru No',
    category:                 'Kategori',
    subject:                  'Konu',
    status:                   'Son Durum',
    date:                     'Başvuru Tarihi',
    detail:                   'Detay Görüntüle',
    ticketDetail:             'Talep Detayı',
    timeline:                 'Zaman Çizelgesi',
    updateStatus:             'Durumu Güncelle',
    note:                     'Not ekle (isteğe bağlı)…',
    save:                     'Kaydet',
    noTickets:                'Henüz talep oluşturmadınız.',
    titleLabel:               'Konu Başlığı',
    titlePlaceholder:         'Kısa bir başlık girin',
    msgLabel:                 'Mesajınız',
    msgPlaceholder:           'Detaylı açıklama yazın…',
    adminBadge:               'Admin',
    created:                  'Oluşturuldu',
    statusChanged:            'Durum Değiştirildi',
    statusOpen:               'Alındı',
    statusInProgress:         'İşlemde',
    statusClosed:             'Cevaplandı',
    statusSubmitted:          'Başvuru Alındı',
    statusReviewing:          'İşlemde',
    statusWaitingDepartment:  'İlgili Birimde',
    statusAnswered:           'Cevaplandı',
    cat0:                     'Şikayet',
    cat1:                     'Öneri',
    cat2:                     'Destek Talebi',
    cat3:                     'Teşekkür',
    cat4:                     'Soru',
    cat5:                     'Bilgi Edinme',
    adminHint:                'Admin:',
    waiting:                  'Lütfen bekleyin…',
    allRequests:              'Tüm Talepler',
    total:                    'toplam',
    filterAll:                'Tümü',
    welcomeBack:              'Hoş geldiniz!',
    loginDesc:                'Hesabınıza giriş yapın',
    noAccount:                'Hesabınız yok mu?',
    invalidCreds:             'Geçersiz bilgiler',
    connError:                'Bağlantı hatası',
    Complaint:                'Şikayet',
    Suggestion:               'Öneri',
    SupportRequest:           'Destek Talebi',
    Request:                  'Destek Talebi',
    Appreciation:             'Teşekkür',
    Question:                 'Soru',
    InfoRequest:              'Bilgi Edinme',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    langUr:                   'اردو',
    langKo:                   '한국어',
    myTicketsSub:             'Hizmet taleplerinizi yönetin ve takip edin.',
    searchPlaceholder:        'Başvuru no veya başlığa göre ara...',
    chartCategory:            'Kategori Dağılımı',
    chartTrend:               'Aylık Durum Trendi (Son 6 Ay)',
    chartDept:                'Departman Sıralaması',
    chartAging:               'Yaşlandırma Analizi',
    chartPerformance:         'Birim Performans Analizi',
    statRate:                 'Çözme Oranı',
    statUnansweredCount:      'Cevapsız',
    statResolved:             'Çözüldü',
    statPending:              'İşlemde',
    statWaiting:              'Bekliyor',
    statUnanswered:           'Cevaplanmadı',
    statTotal:                'Toplam',
    filterMonth:              'Bu Ay',
    filterYear:               'Bu Yıl',
    filterCustom:             'Özel',
    apply:                    'Uygula',
    exportPdf:                'PDF RAPOR AL',
    aging45:                  '45+ GÜN',
    aging60:                  '60+ GÜN',
    aging90:                  '90+ GÜN',
    aging180:                 '180+ GÜN',
    noDeptData:               'Departman verisi yok',
    pdfReportTitle:           'Analitik Performans Raporu',
    pdfOfficialDoc:           'Resmi Analiz Dökümanı',
    pdfGeneratedBy:           'Bu rapor RİMER tarafından otomatik oluşturulmuştur.',
    pdfAllTime:               'Tüm Zamanlar',
    catInfo:                  'Bilgi',
    catThanks:                'Teşekkür',
    perfScore:                'Performans Skoru',
    perfOverdue:              'Gecikmiş',
    perfCritical:             'Kritik',
    perfTransfer:             'Transfer Oranı',
    perfInProgress:           'İşlemde',
    perfExcellent:            'Mükemmel',
    perfGood:                 'İyi',
    perfWarning:              'Dikkat',
    perfCriticalLabel:        'Kritik',
    perfResRate:              'Çözüm Oranı',
    perfOverdueRate:          'Gecikme Oranı',
    chartSatisfaction:        'Memnuniyet Başvurularının Birimlere Göre Dağılımı',
    chartComplaint:           'Şikayet Başvurularının Birimlere Göre Dağılımı',
    chartStaffType:           'Personel Türüne Göre Başvuru Dağılımı',
    staffAcademic:            'Akademik',
    staffAdmin:               'İdari',
    staffWorker:              'İşçi',
    staffStudent:             'Öğrenci',
    staffOther:               'Diğer',
    publicApply:              'Dış Kullanıcı Başvurusu',
    publicTrack:              'Başvuru Sorgulama',
    publicTrackSub:           'Size verilen takip numarası ve e-posta adresinizle başvurunuzun durumunu sorgulayabilirsiniz.',
    personalInfo:             'Kişisel Bilgiler',
    firstName:                'AD',
    lastName:                 'SOYAD',
    idNumber:                 'TC KİMLİK NO',
    jobTitle:                 'ÜNVAN',
    address:                  'ADRES',
    hideInfo:                 'Kişisel Bilgilerim Gizlensin',
    hideInfoSub:              'Personel kimliğimi göremesin',
    required:                 'ZORUNLU',
    optional:                 'OPSİYONEL',
    nextStep:                 'SONRAKİ ADIM',
    prevStep:                 'FORMA DÖN',
    finishApply:              'BAŞVURUYU TAMAMLA',
    cancelApply:              'İPTAL ET VE VAZGEÇ',
    termsTitle:               'TAAHHÜTNAME',
    termsAccept:              'Okudum, onaylıyorum.',
    summary:                  'ÖZET ÖNİZLEME',
    trackButton:              'SORGULA',
    trackResult:              'Sorgu Sonucu',
    newQuery:                 'Yeni Sorgu',
    noDeptAssigned:           'Birim Atanmadı',
    timelineTitle:            'İşlem Geçmişi',
    trackDescription:         'Takip numaranız ve e-posta adresinizle başvurunuzun güncel durumunu izleyin.',
    applySuccess:             'Başvurunuz Başarıyla Alındı!',
    trackingNo:               'Takip Numaranız',
    trackNow:                 'BAŞVURUMU TAKİP ET',
    relevantDept:             'İLGİLİ BİRİM (HEDEF KURUM)',
    selectDept:               'Lütfen birim seçiniz...',
    visitorAction:            'Üye Olmadan (Ziyaretçi) İşlem Yapın',
    newApplication:           'Yeni Başvuru',
    trackApplication:         'Başvuru Takip',
    forgotPassword:           'Şifremi Unuttum',
    copyright:                '© 2026 Rimer İletişim Merkezi. Tüm hakları saklıdır.',
  },

  // ─── English ──────────────────────────────────────────────────────────────
  en: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'Sign In',
    register:                 'Register',
    logout:                   'Sign Out',
    email:                    'Email',
    password:                 'Password',
    passwordConfirm:          'Confirm Password',
    fullName:                 'Full Name',
    submit:                   'Submit',
    sending:                  'Submitting…',
    loading:                  'Loading…',
    saving:                   'Saving…',
    cancel:                   'Cancel',
    back:                     '← Back',
    newTicket:                'New Request',
    myTickets:                'My Requests',
    ticketNo:                 'Request No',
    category:                 'Category',
    subject:                  'Subject',
    status:                   'Status',
    date:                     'Date',
    detail:                   'View Detail',
    ticketDetail:             'Request Detail',
    timeline:                 'Timeline',
    updateStatus:             'Update Status',
    note:                     'Add a note (optional)…',
    save:                     'Save',
    noTickets:                'No requests submitted yet.',
    titleLabel:               'Subject',
    titlePlaceholder:         'Short title',
    msgLabel:                 'Message',
    msgPlaceholder:           'Describe your request in detail…',
    adminBadge:               'Admin',
    created:                  'Created',
    statusChanged:            'Status Changed',
    statusOpen:               'Received',
    statusInProgress:         'In Process',
    statusClosed:             'Resolved',
    statusSubmitted:          'Submitted',
    statusReviewing:          'In Review',
    statusWaitingDepartment:  'At Department',
    statusAnswered:           'Resolved',
    cat0:                     'Complaint',
    cat1:                     'Suggestion',
    cat2:                     'Support Request',
    cat3:                     'Appreciation',
    cat4:                     'Question',
    cat5:                     'Info Request',
    adminHint:                'Admin:',
    waiting:                  'Please wait…',
    allRequests:              'All Requests',
    total:                    'total',
    filterAll:                'All',
    welcomeBack:              'Welcome back!',
    loginDesc:                'Sign in to your account',
    noAccount:                "Don't have an account?",
    invalidCreds:             'Invalid credentials',
    connError:                'Connection error',
    Complaint:                'Complaint',
    Suggestion:               'Suggestion',
    SupportRequest:           'Support Request',
    Request:                  'Support Request',
    Appreciation:             'Appreciation',
    Question:                 'Question',
    InfoRequest:              'Info Request',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    langUr:                   'اردو',
    langKo:                   '한국어',
    myTicketsSub:             'Manage and track your service requests.',
    searchPlaceholder:        'Search by reference number or title...',
    chartCategory:            'Category Distribution',
    chartTrend:               'Monthly Status Trend (Last 6 Months)',
    chartDept:                'Department Ranking',
    chartAging:               'Aging Analysis',
    chartPerformance:         'Unit Performance Analysis',
    statRate:                 'Resolution Rate',
    statUnansweredCount:      'Unanswered',
    statResolved:             'Resolved',
    statPending:              'In Process',
    statWaiting:              'Waiting',
    statUnanswered:           'Unanswered',
    statTotal:                'Total',
    filterMonth:              'This Month',
    filterYear:               'This Year',
    filterCustom:             'Custom',
    apply:                    'Apply',
    exportPdf:                'EXPORT PDF REPORT',
    aging45:                  '45+ DAYS',
    aging60:                  '60+ DAYS',
    aging90:                  '90+ DAYS',
    aging180:                 '180+ DAYS',
    noDeptData:               'No department data',
    pdfReportTitle:           'Analytical Performance Report',
    pdfOfficialDoc:           'Official Analysis Document',
    pdfGeneratedBy:           'This report was automatically generated by RİMER.',
    pdfAllTime:               'All Time',
    catInfo:                  'Information',
    catThanks:                'Appreciation',
    perfScore:                'Performance Score',
    perfOverdue:              'Overdue',
    perfCritical:             'Critical',
    perfTransfer:             'Transfer Rate',
    perfInProgress:           'In Progress',
    perfExcellent:            'Excellent',
    perfGood:                 'Good',
    perfWarning:              'Warning',
    perfCriticalLabel:        'Critical',
    perfResRate:              'Resolution Rate',
    perfOverdueRate:          'Overdue Rate',
    chartSatisfaction:        'Satisfaction Applications by Department',
    chartComplaint:           'Complaint Applications by Department',
    chartStaffType:           'Applications by Staff Type',
    staffAcademic:            'Academic',
    staffAdmin:               'Administrative',
    staffWorker:              'Worker',
    staffStudent:             'Student',
    staffOther:               'Other',
    publicApply:              'Public Application',
    publicTrack:              'Application Tracking',
    publicTrackSub:           'Check the status of your application using the tracking code and email address provided.',
    personalInfo:             'Personal Information',
    firstName:                'FIRST NAME',
    lastName:                 'LAST NAME',
    idNumber:                 'ID NUMBER',
    jobTitle:                 'TITLE',
    address:                  'ADDRESS',
    hideInfo:                 'Hide My Personal Information',
    hideInfoSub:              'Staff cannot see my identity',
    required:                 'REQUIRED',
    optional:                 'OPTIONAL',
    nextStep:                 'NEXT STEP',
    prevStep:                 'BACK TO FORM',
    finishApply:              'FINISH APPLICATION',
    cancelApply:              'CANCEL AND QUIT',
    termsTitle:               'TERMS & CONDITIONS',
    termsAccept:              'I have read and agree.',
    summary:                  'SUMMARY PREVIEW',
    trackButton:              'TRACK',
    trackResult:              'Query Result',
    newQuery:                 'New Query',
    noDeptAssigned:           'No Unit Assigned',
    timelineTitle:            'Process History',
    trackDescription:         'Follow the current status of your application with your tracking number and email address.',
    applySuccess:             'Your Application Has Been Successfully Received!',
    trackingNo:               'Your Tracking Number',
    trackNow:                 'TRACK MY APPLICATION',
    relevantDept:             'RELEVANT UNIT (TARGET INSTITUTION)',
    selectDept:               'Please select a unit...',
    visitorAction:            'Continue as Visitor (No Account Required)',
    newApplication:           'New Application',
    trackApplication:         'Track Application',
    forgotPassword:           'Forgot Password?',
    copyright:                '© 2026 Rimer Communication Center. All rights reserved.',
  },

  // ─── 中文 (Simplified Chinese) ─────────────────────────────────────────────
  zh: {
    ...BASE,
    appName:                  'Rimer',
    login:                    '登录',
    register:                 '注册',
    logout:                   '退出',
    email:                    '电子邮箱',
    password:                 '密码',
    passwordConfirm:          '确认密码',
    fullName:                 '姓名',
    submit:                   '提交',
    sending:                  '提交中…',
    loading:                  '加载中…',
    saving:                   '保存中…',
    cancel:                   '取消',
    back:                     '← 返回',
    newTicket:                '新申请',
    myTickets:                '我的申请',
    ticketNo:                 '申请编号',
    category:                 '类别',
    subject:                  '主题',
    status:                   '状态',
    date:                     '申请日期',
    detail:                   '查看详情',
    ticketDetail:             '申请详情',
    timeline:                 '时间线',
    updateStatus:             '更新状态',
    note:                     '添加备注（可选）…',
    save:                     '保存',
    noTickets:                '尚未提交任何申请。',
    titleLabel:               '主题',
    titlePlaceholder:         '简短标题',
    msgLabel:                 '消息',
    msgPlaceholder:           '详细描述您的申请…',
    adminBadge:               '管理员',
    created:                  '已创建',
    statusChanged:            '状态已更改',
    statusOpen:               '已收到',
    statusInProgress:         '处理中',
    statusClosed:             '已解决',
    statusSubmitted:          '已提交',
    statusReviewing:          '审核中',
    statusWaitingDepartment:  '在相关部门',
    statusAnswered:           '已答复',
    cat0:                     '投诉',
    cat1:                     '建议',
    cat2:                     '支持请求',
    cat3:                     '感谢',
    cat4:                     '问题',
    cat5:                     '信息请求',
    adminHint:                '管理员:',
    waiting:                  '请稍候…',
    allRequests:              '所有申请',
    total:                    '总计',
    filterAll:                '全部',
    welcomeBack:              '欢迎回来！',
    loginDesc:                '登录您的账户',
    noAccount:                '没有账户？',
    invalidCreds:             '凭据无效',
    connError:                '连接错误',
    Complaint:                '投诉',
    Suggestion:               '建议',
    SupportRequest:           '支持请求',
    Request:                  '支持请求',
    Appreciation:             '感谢',
    Question:                 '问题',
    InfoRequest:              '信息请求',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    myTicketsSub:             '管理和跟踪您的服务申请。',
    searchPlaceholder:        '按参考号或标题搜索...',
    chartCategory:            '类别分布',
    chartTrend:               '月度状态趋势（近6个月）',
    chartDept:                '部门排名',
    chartAging:               '老化分析',
    chartPerformance:         '部门绩效分析',
    statRate:                 '解决率',
    statUnansweredCount:      '未答复',
    statResolved:             '已解决',
    statPending:              '处理中',
    statWaiting:              '等待中',
    statUnanswered:           '未答复',
    statTotal:                '总计',
    filterMonth:              '本月',
    filterYear:               '本年',
    filterCustom:             '自定义',
    apply:                    '应用',
    exportPdf:                '导出PDF报告',
    aging45:                  '45+天',
    aging60:                  '60+天',
    aging90:                  '90+天',
    aging180:                 '180+天',
    noDeptData:               '无部门数据',
    pdfReportTitle:           '分析性能报告',
    pdfOfficialDoc:           '官方分析文件',
    pdfGeneratedBy:           '此报告由RİMER自动生成。',
    pdfAllTime:               '所有时间',
    catInfo:                  '信息',
    catThanks:                '感谢',
    perfScore:                '绩效分数',
    perfOverdue:              '逾期',
    perfCritical:             '紧急',
    perfTransfer:             '转移率',
    perfInProgress:           '进行中',
    perfExcellent:            '优秀',
    perfGood:                 '良好',
    perfWarning:              '警告',
    perfCriticalLabel:        '紧急',
    perfResRate:              '解决率',
    perfOverdueRate:          '逾期率',
    chartSatisfaction:        '按部门分类的满意度申请',
    chartComplaint:           '按部门分类的投诉申请',
    chartStaffType:           '按员工类型分类的申请',
    staffAcademic:            '学术',
    staffAdmin:               '行政',
    staffWorker:              '工人',
    staffStudent:             '学生',
    staffOther:               '其他',
    publicApply:              '公众申请',
    publicTrack:              '申请查询',
    publicTrackSub:           '使用提供给您的跟踪号码和电子邮件地址查询申请状态。',
    personalInfo:             '个人信息',
    firstName:                '名',
    lastName:                 '姓',
    idNumber:                 '身份证号',
    jobTitle:                 '职称',
    address:                  '地址',
    hideInfo:                 '隐藏我的个人信息',
    hideInfoSub:              '工作人员无法看到我的身份',
    required:                 '必填',
    optional:                 '可选',
    nextStep:                 '下一步',
    prevStep:                 '返回表格',
    finishApply:              '完成申请',
    cancelApply:              '取消并退出',
    termsTitle:               '条款与条件',
    termsAccept:              '我已阅读并同意。',
    summary:                  '摘要预览',
    trackButton:              '查询',
    trackResult:              '查询结果',
    newQuery:                 '新查询',
    noDeptAssigned:           '未分配部门',
    timelineTitle:            '处理历史',
    trackDescription:         '使用跟踪号码和电子邮件地址跟踪申请的当前状态。',
    applySuccess:             '您的申请已成功收到！',
    trackingNo:               '您的跟踪号码',
    trackNow:                 '跟踪我的申请',
    relevantDept:             '相关部门（目标机构）',
    selectDept:               '请选择部门...',
    visitorAction:            '作为访客继续（无需账户）',
    newApplication:           '新申请',
    trackApplication:         '申请跟踪',
    forgotPassword:           '忘记密码？',
    copyright:                '© 2026 Rimer 通信中心。保留所有权利。',
  },

  // ─── Azərbaycanca ────────────────────────────────────────────────────────
  az: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'Daxil ol',
    register:                 'Qeydiyyat',
    logout:                   'Çıxış',
    email:                    'E-poçt',
    password:                 'Şifrə',
    passwordConfirm:          'Şifrəni təkrarla',
    fullName:                 'Ad Soyad',
    submit:                   'Göndər',
    sending:                  'Göndərilir…',
    loading:                  'Yüklənir…',
    saving:                   'Saxlanılır…',
    cancel:                   'Ləğv et',
    back:                     '← Geri',
    newTicket:                'Yeni müraciət',
    myTickets:                'Müraciətlərim',
    ticketNo:                 'Müraciət nömrəsi',
    category:                 'Kateqoriya',
    subject:                  'Mövzu',
    status:                   'Status',
    date:                     'Müraciət tarixi',
    detail:                   'Ətraflı bax',
    ticketDetail:             'Müraciət təfərrüatı',
    timeline:                 'Zaman xətti',
    updateStatus:             'Statusu yenilə',
    note:                     'Qeyd əlavə et (isteğe bağlı)…',
    save:                     'Saxla',
    noTickets:                'Hələ müraciət etməmisiniz.',
    titleLabel:               'Mövzu başlığı',
    titlePlaceholder:         'Qısa başlıq daxil edin',
    msgLabel:                 'Mesajınız',
    msgPlaceholder:           'Ətraflı izahat yazın…',
    adminBadge:               'Admin',
    created:                  'Yaradıldı',
    statusChanged:            'Status dəyişdirildi',
    statusOpen:               'Qəbul edildi',
    statusInProgress:         'İcradadır',
    statusClosed:             'Cavablandırıldı',
    statusSubmitted:          'Müraciət qəbul edildi',
    statusReviewing:          'Baxılır',
    statusWaitingDepartment:  'Bölmədə',
    statusAnswered:           'Cavablandırıldı',
    cat0:                     'Şikayət',
    cat1:                     'Təklif',
    cat2:                     'Dəstək tələbi',
    cat3:                     'Təşəkkür',
    cat4:                     'Sual',
    cat5:                     'Məlumat tələbi',
    adminHint:                'Admin:',
    waiting:                  'Lütfən gözləyin…',
    allRequests:              'Bütün müraciətlər',
    total:                    'cəmi',
    filterAll:                'Hamısı',
    welcomeBack:              'Xoş gəldiniz!',
    loginDesc:                'Hesabınıza daxil olun',
    noAccount:                'Hesabınız yoxdur?',
    invalidCreds:             'Yanlış məlumatlar',
    connError:                'Bağlantı xətası',
    Complaint:                'Şikayət',
    Suggestion:               'Təklif',
    SupportRequest:           'Dəstək tələbi',
    Request:                  'Dəstək tələbi',
    Appreciation:             'Təşəkkür',
    Question:                 'Sual',
    InfoRequest:              'Məlumat tələbi',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    myTicketsSub:             'Xidmət müraciətlərinizi idarə edin və izləyin.',
    searchPlaceholder:        'İstinad nömrəsi və ya başlığa görə axtar...',
    chartCategory:            'Kateqoriya bölgüsü',
    chartTrend:               'Aylıq status trendi (Son 6 ay)',
    chartDept:                'Şöbə reytinqi',
    chartAging:               'Köhnəlmə analizi',
    chartPerformance:         'Bölmə performans analizi',
    statRate:                 'Həll dərəcəsi',
    statUnansweredCount:      'Cavabsız',
    statResolved:             'Həll edildi',
    statPending:              'İcradadır',
    statWaiting:              'Gözlənilir',
    statUnanswered:           'Cavabsız',
    statTotal:                'Cəmi',
    filterMonth:              'Bu ay',
    filterYear:               'Bu il',
    filterCustom:             'Xüsusi',
    apply:                    'Tətbiq et',
    exportPdf:                'PDF HESABAT',
    aging45:                  '45+ GÜN',
    aging60:                  '60+ GÜN',
    aging90:                  '90+ GÜN',
    aging180:                 '180+ GÜN',
    noDeptData:               'Şöbə məlumatı yoxdur',
    pdfReportTitle:           'Analitik Performans Hesabatı',
    pdfOfficialDoc:           'Rəsmi Analiz Sənədi',
    pdfGeneratedBy:           'Bu hesabat RİMER tərəfindən avtomatik yaradılmışdır.',
    pdfAllTime:               'Bütün zamanlar',
    catInfo:                  'Məlumat',
    catThanks:                'Təşəkkür',
    perfScore:                'Performans skoru',
    perfOverdue:              'Gecikmiş',
    perfCritical:             'Kritik',
    perfTransfer:             'Transfer dərəcəsi',
    perfInProgress:           'İcradadır',
    perfExcellent:            'Əla',
    perfGood:                 'Yaxşı',
    perfWarning:              'Diqqət',
    perfCriticalLabel:        'Kritik',
    perfResRate:              'Həll dərəcəsi',
    perfOverdueRate:          'Gecikməsi dərəcəsi',
    chartSatisfaction:        'Məmnuniyyət müraciətlərinin şöbələrə görə bölgüsü',
    chartComplaint:           'Şikayət müraciətlərinin şöbələrə görə bölgüsü',
    chartStaffType:           'İşçi növünə görə müraciət bölgüsü',
    staffAcademic:            'Akademik',
    staffAdmin:               'İnzibati',
    staffWorker:              'İşçi',
    staffStudent:             'Tələbə',
    staffOther:               'Digər',
    publicApply:              'İctimai müraciət',
    publicTrack:              'Müraciət sorğusu',
    publicTrackSub:           'Verilən izləmə nömrəsi və e-poçt ünvanınızla müraciətinizin statusunu yoxlaya bilərsiniz.',
    personalInfo:             'Şəxsi məlumatlar',
    firstName:                'AD',
    lastName:                 'SOYAD',
    idNumber:                 'ŞƏXSİYYƏT VƏSİQƏSİ NÖMRƏSİ',
    jobTitle:                 'VƏZİFƏ',
    address:                  'ÜNVAN',
    hideInfo:                 'Şəxsi məlumatlarımı gizlət',
    hideInfoSub:              'İşçilər kimliyimi görə bilməsin',
    required:                 'MƏCBURİ',
    optional:                 'İXTİYARİ',
    nextStep:                 'NÖVBƏTİ ADDIM',
    prevStep:                 'FORMAYA QAYIT',
    finishApply:              'MÜRACİƏTİ TAMAMLA',
    cancelApply:              'LƏĞV ET VƏ ÇIXIM',
    termsTitle:               'ÖHDƏÇILIK',
    termsAccept:              'Oxudum, qəbul edirəm.',
    summary:                  'XÜLASƏLİ ÖN BAXIŞ',
    trackButton:              'SORĞU',
    trackResult:              'Sorğu nəticəsi',
    newQuery:                 'Yeni sorğu',
    noDeptAssigned:           'Bölmə təyin edilməyib',
    timelineTitle:            'Əməliyyat tarixi',
    trackDescription:         'İzləmə nömrəsi və e-poçt ünvanınızla müraciətinizin cari statusunu izləyin.',
    applySuccess:             'Müraciətiniz uğurla qəbul edildi!',
    trackingNo:               'İzləmə nömrəniz',
    trackNow:                 'MÜRACİƏTİMİ İZLƏ',
    relevantDept:             'ƏLAQƏDAR BÖLMƏ (HƏDƏF QURUM)',
    selectDept:               'Zəhmət olmasa bölmə seçin...',
    visitorAction:            'Qeydiyyatsız (Ziyarətçi) əməliyyat edin',
    newApplication:           'Yeni müraciət',
    trackApplication:         'Müraciəti izlə',
    forgotPassword:           'Şifrəmi unutdum',
    copyright:                '© 2026 Rimer Rabitə Mərkəzi. Bütün hüquqlar qorunur.',
  },

  // ─── Русский ──────────────────────────────────────────────────────────────
  ru: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'Войти',
    register:                 'Регистрация',
    logout:                   'Выйти',
    email:                    'Эл. почта',
    password:                 'Пароль',
    passwordConfirm:          'Подтверждение пароля',
    fullName:                 'Полное имя',
    submit:                   'Отправить',
    sending:                  'Отправка…',
    loading:                  'Загрузка…',
    saving:                   'Сохранение…',
    cancel:                   'Отмена',
    back:                     '← Назад',
    newTicket:                'Новое обращение',
    myTickets:                'Мои обращения',
    ticketNo:                 'Номер обращения',
    category:                 'Категория',
    subject:                  'Тема',
    status:                   'Статус',
    date:                     'Дата обращения',
    detail:                   'Подробнее',
    ticketDetail:             'Детали обращения',
    timeline:                 'Хронология',
    updateStatus:             'Обновить статус',
    note:                     'Добавить примечание (необязательно)…',
    save:                     'Сохранить',
    noTickets:                'Вы ещё не подавали обращений.',
    titleLabel:               'Тема',
    titlePlaceholder:         'Краткий заголовок',
    msgLabel:                 'Сообщение',
    msgPlaceholder:           'Подробно опишите ваше обращение…',
    adminBadge:               'Администратор',
    created:                  'Создано',
    statusChanged:            'Статус изменён',
    statusOpen:               'Получено',
    statusInProgress:         'В обработке',
    statusClosed:             'Решено',
    statusSubmitted:          'Подано',
    statusReviewing:          'На рассмотрении',
    statusWaitingDepartment:  'В отделе',
    statusAnswered:           'Отвечено',
    cat0:                     'Жалоба',
    cat1:                     'Предложение',
    cat2:                     'Запрос поддержки',
    cat3:                     'Благодарность',
    cat4:                     'Вопрос',
    cat5:                     'Запрос информации',
    adminHint:                'Администратор:',
    waiting:                  'Пожалуйста, подождите…',
    allRequests:              'Все обращения',
    total:                    'всего',
    filterAll:                'Все',
    welcomeBack:              'Добро пожаловать!',
    loginDesc:                'Войдите в свой аккаунт',
    noAccount:                'Нет аккаунта?',
    invalidCreds:             'Неверные данные',
    connError:                'Ошибка соединения',
    Complaint:                'Жалоба',
    Suggestion:               'Предложение',
    SupportRequest:           'Запрос поддержки',
    Request:                  'Запрос поддержки',
    Appreciation:             'Благодарность',
    Question:                 'Вопрос',
    InfoRequest:              'Запрос информации',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    myTicketsSub:             'Управляйте своими обращениями и отслеживайте их.',
    searchPlaceholder:        'Поиск по номеру или теме...',
    chartCategory:            'Распределение по категориям',
    chartTrend:               'Ежемесячный тренд статусов (последние 6 месяцев)',
    chartDept:                'Рейтинг отделов',
    chartAging:               'Анализ сроков',
    chartPerformance:         'Анализ эффективности отдела',
    statRate:                 'Коэффициент решения',
    statUnansweredCount:      'Без ответа',
    statResolved:             'Решено',
    statPending:              'В обработке',
    statWaiting:              'Ожидание',
    statUnanswered:           'Без ответа',
    statTotal:                'Итого',
    filterMonth:              'Этот месяц',
    filterYear:               'Этот год',
    filterCustom:             'Настроить',
    apply:                    'Применить',
    exportPdf:                'ЭКСПОРТ PDF',
    aging45:                  '45+ ДНЕЙ',
    aging60:                  '60+ ДНЕЙ',
    aging90:                  '90+ ДНЕЙ',
    aging180:                 '180+ ДНЕЙ',
    noDeptData:               'Нет данных отдела',
    pdfReportTitle:           'Аналитический отчёт о производительности',
    pdfOfficialDoc:           'Официальный аналитический документ',
    pdfGeneratedBy:           'Этот отчёт был автоматически создан RİMER.',
    pdfAllTime:               'Всё время',
    catInfo:                  'Информация',
    catThanks:                'Благодарность',
    perfScore:                'Оценка производительности',
    perfOverdue:              'Просрочено',
    perfCritical:             'Критическое',
    perfTransfer:             'Уровень передачи',
    perfInProgress:           'В процессе',
    perfExcellent:            'Отлично',
    perfGood:                 'Хорошо',
    perfWarning:              'Предупреждение',
    perfCriticalLabel:        'Критическое',
    perfResRate:              'Уровень решения',
    perfOverdueRate:          'Уровень просрочки',
    chartSatisfaction:        'Обращения по удовлетворённости по отделам',
    chartComplaint:           'Жалобы по отделам',
    chartStaffType:           'Обращения по типу персонала',
    staffAcademic:            'Академический',
    staffAdmin:               'Административный',
    staffWorker:              'Рабочий',
    staffStudent:             'Студент',
    staffOther:               'Другое',
    publicApply:              'Публичное обращение',
    publicTrack:              'Отслеживание обращения',
    publicTrackSub:           'Проверьте статус вашего обращения с помощью трекинг-номера и адреса электронной почты.',
    personalInfo:             'Личные данные',
    firstName:                'ИМЯ',
    lastName:                 'ФАМИЛИЯ',
    idNumber:                 'НОМЕР УДОСТОВЕРЕНИЯ',
    jobTitle:                 'ДОЛЖНОСТЬ',
    address:                  'АДРЕС',
    hideInfo:                 'Скрыть мои личные данные',
    hideInfoSub:              'Сотрудники не смогут видеть мою личность',
    required:                 'ОБЯЗАТЕЛЬНО',
    optional:                 'НЕОБЯЗАТЕЛЬНО',
    nextStep:                 'СЛЕДУЮЩИЙ ШАГ',
    prevStep:                 'ВЕРНУТЬСЯ К ФОРМЕ',
    finishApply:              'ЗАВЕРШИТЬ ОБРАЩЕНИЕ',
    cancelApply:              'ОТМЕНИТЬ И ВЫЙТИ',
    termsTitle:               'УСЛОВИЯ И ПОЛОЖЕНИЯ',
    termsAccept:              'Я прочитал и согласен.',
    summary:                  'ПРЕДВАРИТЕЛЬНЫЙ ПРОСМОТР',
    trackButton:              'ПОИСК',
    trackResult:              'Результат запроса',
    newQuery:                 'Новый запрос',
    noDeptAssigned:           'Отдел не назначен',
    timelineTitle:            'История обработки',
    trackDescription:         'Отслеживайте текущий статус вашего обращения с помощью трекинг-номера и адреса электронной почты.',
    applySuccess:             'Ваше обращение успешно принято!',
    trackingNo:               'Ваш номер отслеживания',
    trackNow:                 'ОТСЛЕДИТЬ МОЁ ОБРАЩЕНИЕ',
    relevantDept:             'СООТВЕТСТВУЮЩИЙ ОТДЕЛ (ЦЕЛЕВОЕ УЧРЕЖДЕНИЕ)',
    selectDept:               'Пожалуйста, выберите отдел...',
    visitorAction:            'Продолжить как гость (без регистрации)',
    newApplication:           'Новое обращение',
    trackApplication:         'Отследить обращение',
    forgotPassword:           'Забыли пароль?',
    copyright:                '© 2026 Rimer Центр связи. Все права защищены.',
  },

  // ─── Қазақша ──────────────────────────────────────────────────────────────
  kk: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'Кіру',
    register:                 'Тіркелу',
    logout:                   'Шығу',
    email:                    'Электрондық пошта',
    password:                 'Құпия сөз',
    passwordConfirm:          'Құпия сөзді растаңыз',
    fullName:                 'Толық аты-жөні',
    submit:                   'Жіберу',
    sending:                  'Жіберілуде…',
    loading:                  'Жүктелуде…',
    saving:                   'Сақталуда…',
    cancel:                   'Болдырмау',
    back:                     '← Артқа',
    newTicket:                'Жаңа өтініш',
    myTickets:                'Менің өтініштерім',
    ticketNo:                 'Өтініш нөмірі',
    category:                 'Санат',
    subject:                  'Тақырып',
    status:                   'Мәртебесі',
    date:                     'Өтініш берілген күн',
    detail:                   'Толығырақ',
    ticketDetail:             'Өтініш мәліметтері',
    timeline:                 'Уақыт шкаласы',
    updateStatus:             'Мәртебені жаңарту',
    note:                     'Ескерту қосу (міндетті емес)…',
    save:                     'Сақтау',
    noTickets:                'Сіз әлі өтініш бермедіңіз.',
    titleLabel:               'Тақырып',
    titlePlaceholder:         'Қысқа тақырып',
    msgLabel:                 'Хабарлама',
    msgPlaceholder:           'Өтінішіңізді толық сипаттаңыз…',
    adminBadge:               'Әкімші',
    created:                  'Жасалды',
    statusChanged:            'Мәртебе өзгертілді',
    statusOpen:               'Алынды',
    statusInProgress:         'Өңделуде',
    statusClosed:             'Шешілді',
    statusSubmitted:          'Берілді',
    statusReviewing:          'Қаралуда',
    statusWaitingDepartment:  'Бөлімде',
    statusAnswered:           'Жауап берілді',
    cat0:                     'Шағым',
    cat1:                     'Ұсыныс',
    cat2:                     'Қолдау сұрауы',
    cat3:                     'Алғыс',
    cat4:                     'Сұрақ',
    cat5:                     'Ақпарат сұрауы',
    adminHint:                'Әкімші:',
    waiting:                  'Күтіңіз…',
    allRequests:              'Барлық өтініштер',
    total:                    'барлығы',
    filterAll:                'Барлығы',
    welcomeBack:              'Қош келдіңіз!',
    loginDesc:                'Тіркелгіңізге кіріңіз',
    noAccount:                'Тіркелгіңіз жоқ па?',
    invalidCreds:             'Жарамсыз деректер',
    connError:                'Қосылу қатесі',
    Complaint:                'Шағым',
    Suggestion:               'Ұсыныс',
    SupportRequest:           'Қолдау сұрауы',
    Request:                  'Қолдау сұрауы',
    Appreciation:             'Алғыс',
    Question:                 'Сұрақ',
    InfoRequest:              'Ақпарат сұрауы',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    myTicketsSub:             'Қызмет өтініштерін басқарыңыз және бақылаңыз.',
    searchPlaceholder:        'Нөмір немесе тақырып бойынша іздеу...',
    chartCategory:            'Санат бойынша бөлу',
    chartTrend:               'Ай сайынғы мәртебе тренді (соңғы 6 ай)',
    chartDept:                'Бөлім рейтингі',
    chartAging:               'Мерзімдерді талдау',
    chartPerformance:         'Бөлім өнімділігін талдау',
    statRate:                 'Шешу деңгейі',
    statUnansweredCount:      'Жауапсыз',
    statResolved:             'Шешілді',
    statPending:              'Өңделуде',
    statWaiting:              'Күтуде',
    statUnanswered:           'Жауапсыз',
    statTotal:                'Барлығы',
    filterMonth:              'Осы ай',
    filterYear:               'Осы жыл',
    filterCustom:             'Арнаулы',
    apply:                    'Қолдану',
    exportPdf:                'PDF ЕСЕП',
    aging45:                  '45+ КҮН',
    aging60:                  '60+ КҮН',
    aging90:                  '90+ КҮН',
    aging180:                 '180+ КҮН',
    noDeptData:               'Бөлім деректері жоқ',
    pdfReportTitle:           'Талдамалық өнімділік есебі',
    pdfOfficialDoc:           'Ресми талдау құжаты',
    pdfGeneratedBy:           'Бұл есепті RİMER автоматты түрде жасаған.',
    pdfAllTime:               'Барлық уақыт',
    catInfo:                  'Ақпарат',
    catThanks:                'Алғыс',
    perfScore:                'Өнімділік ұпайы',
    perfOverdue:              'Мерзімі өткен',
    perfCritical:             'Сыни',
    perfTransfer:             'Аудару деңгейі',
    perfInProgress:           'Өңделуде',
    perfExcellent:            'Өте жақсы',
    perfGood:                 'Жақсы',
    perfWarning:              'Ескерту',
    perfCriticalLabel:        'Сыни',
    perfResRate:              'Шешу деңгейі',
    perfOverdueRate:          'Кешіктіру деңгейі',
    chartSatisfaction:        'Бөлімдер бойынша қанағаттану өтініштері',
    chartComplaint:           'Бөлімдер бойынша шағымдар',
    chartStaffType:           'Қызметкер түрі бойынша өтініштер',
    staffAcademic:            'Академиялық',
    staffAdmin:               'Әкімшілік',
    staffWorker:              'Жұмысшы',
    staffStudent:             'Студент',
    staffOther:               'Басқа',
    publicApply:              'Жалпы өтініш',
    publicTrack:              'Өтінішті бақылау',
    publicTrackSub:           'Берілген бақылау нөмірі мен электрондық пошта арқылы өтінішіңіздің мәртебесін тексеріңіз.',
    personalInfo:             'Жеке ақпарат',
    firstName:                'АТЫ',
    lastName:                 'ТЕГІ',
    idNumber:                 'ЖЕКЕ КУӘЛІК НӨМІРІ',
    jobTitle:                 'ЛАУАЗЫМ',
    address:                  'МЕКЕНЖАЙ',
    hideInfo:                 'Жеке ақпаратымды жасыру',
    hideInfoSub:              'Қызметкерлер менің жеке басымды көре алмасын',
    required:                 'МІНДЕТТІ',
    optional:                 'МІНДЕТТІ ЕМЕС',
    nextStep:                 'КЕЛЕСІ ҚАДАМ',
    prevStep:                 'ФОРМАҒА ҚАЙТУ',
    finishApply:              'ӨТІНІШТІ АЯҚТАУ',
    cancelApply:              'БОЛДЫРМАУ ЖӘНЕ ШЫҒУ',
    termsTitle:               'ШАРТТАР МЕН ЕРЕЖЕЛЕР',
    termsAccept:              'Оқып шықтым, келісемін.',
    summary:                  'ҚЫСҚАША ШОЛУ',
    trackButton:              'ІЗДЕУ',
    trackResult:              'Сұраныс нәтижесі',
    newQuery:                 'Жаңа сұраныс',
    noDeptAssigned:           'Бөлім тағайындалмаған',
    timelineTitle:            'Өңдеу тарихы',
    trackDescription:         'Бақылау нөмірі мен электрондық пошта арқылы өтінішіңіздің ағымдағы мәртебесін бақылаңыз.',
    applySuccess:             'Өтінішіңіз сәтті қабылданды!',
    trackingNo:               'Бақылау нөміріңіз',
    trackNow:                 'ӨТІНІШІМДІ БАҚЫЛАУ',
    relevantDept:             'ТИІСТІ БӨЛІМ (МАҚСАТ МЕКЕМЕ)',
    selectDept:               'Бөлімді таңдаңыз...',
    visitorAction:            'Қонақ ретінде жалғастырыңыз (тіркеусіз)',
    newApplication:           'Жаңа өтініш',
    trackApplication:         'Өтінішті бақылау',
    forgotPassword:           'Құпия сөзді ұмыттыңыз ба?',
    copyright:                '© 2026 Rimer Байланыс Орталығы. Барлық құқықтар қорғалған.',
  },

  // ─── العربية ──────────────────────────────────────────────────────────────
  ar: {
    ...BASE,
    appName:                  'ريمر',
    login:                    'تسجيل الدخول',
    register:                 'إنشاء حساب',
    logout:                   'تسجيل الخروج',
    email:                    'البريد الإلكتروني',
    password:                 'كلمة المرور',
    passwordConfirm:          'تأكيد كلمة المرور',
    fullName:                 'الاسم الكامل',
    submit:                   'إرسال',
    sending:                  'جارٍ الإرسال…',
    loading:                  'جارٍ التحميل…',
    saving:                   'جارٍ الحفظ…',
    cancel:                   'إلغاء',
    back:                     '→ رجوع',
    newTicket:                'طلب جديد',
    myTickets:                'طلباتي',
    ticketNo:                 'رقم الطلب',
    category:                 'الفئة',
    subject:                  'الموضوع',
    status:                   'الحالة',
    date:                     'تاريخ الطلب',
    detail:                   'عرض التفاصيل',
    ticketDetail:             'تفاصيل الطلب',
    timeline:                 'الجدول الزمني',
    updateStatus:             'تحديث الحالة',
    note:                     'أضف ملاحظة (اختياري)…',
    save:                     'حفظ',
    noTickets:                'لم تقدم أي طلبات بعد.',
    titleLabel:               'الموضوع',
    titlePlaceholder:         'عنوان مختصر',
    msgLabel:                 'الرسالة',
    msgPlaceholder:           'صف طلبك بالتفصيل…',
    adminBadge:               'مسؤول',
    created:                  'تم الإنشاء',
    statusChanged:            'تم تغيير الحالة',
    statusOpen:               'تم الاستلام',
    statusInProgress:         'قيد المعالجة',
    statusClosed:             'تم الحل',
    statusSubmitted:          'تم التقديم',
    statusReviewing:          'قيد المراجعة',
    statusWaitingDepartment:  'لدى القسم',
    statusAnswered:           'تم الرد',
    cat0:                     'شكوى',
    cat1:                     'اقتراح',
    cat2:                     'طلب دعم',
    cat3:                     'شكر وتقدير',
    cat4:                     'سؤال',
    cat5:                     'طلب معلومات',
    adminHint:                'المسؤول:',
    waiting:                  'يرجى الانتظار…',
    allRequests:              'جميع الطلبات',
    total:                    'الإجمالي',
    filterAll:                'الكل',
    welcomeBack:              'مرحباً بعودتك!',
    loginDesc:                'سجّل الدخول إلى حسابك',
    noAccount:                'ليس لديك حساب؟',
    invalidCreds:             'بيانات غير صحيحة',
    connError:                'خطأ في الاتصال',
    Complaint:                'شكوى',
    Suggestion:               'اقتراح',
    SupportRequest:           'طلب دعم',
    Request:                  'طلب دعم',
    Appreciation:             'شكر وتقدير',
    Question:                 'سؤال',
    InfoRequest:              'طلب معلومات',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    myTicketsSub:             'إدارة طلبات الخدمة وتتبعها.',
    searchPlaceholder:        'البحث برقم المرجع أو العنوان...',
    chartCategory:            'توزيع الفئات',
    chartTrend:               'اتجاه الحالة الشهرية (آخر 6 أشهر)',
    chartDept:                'ترتيب الأقسام',
    chartAging:               'تحليل الأعمار',
    chartPerformance:         'تحليل أداء الوحدة',
    statRate:                 'معدل الحل',
    statUnansweredCount:      'بدون إجابة',
    statResolved:             'تم الحل',
    statPending:              'قيد المعالجة',
    statWaiting:              'في الانتظار',
    statUnanswered:           'بدون إجابة',
    statTotal:                'الإجمالي',
    filterMonth:              'هذا الشهر',
    filterYear:               'هذا العام',
    filterCustom:             'مخصص',
    apply:                    'تطبيق',
    exportPdf:                'تصدير تقرير PDF',
    aging45:                  '+45 يوماً',
    aging60:                  '+60 يوماً',
    aging90:                  '+90 يوماً',
    aging180:                 '+180 يوماً',
    noDeptData:               'لا توجد بيانات قسم',
    pdfReportTitle:           'تقرير الأداء التحليلي',
    pdfOfficialDoc:           'وثيقة التحليل الرسمية',
    pdfGeneratedBy:           'تم إنشاء هذا التقرير تلقائياً بواسطة RİMER.',
    pdfAllTime:               'كل الأوقات',
    catInfo:                  'معلومات',
    catThanks:                'شكر وتقدير',
    perfScore:                'درجة الأداء',
    perfOverdue:              'متأخر',
    perfCritical:             'حرج',
    perfTransfer:             'معدل النقل',
    perfInProgress:           'قيد التنفيذ',
    perfExcellent:            'ممتاز',
    perfGood:                 'جيد',
    perfWarning:              'تحذير',
    perfCriticalLabel:        'حرج',
    perfResRate:              'معدل الحل',
    perfOverdueRate:          'معدل التأخير',
    chartSatisfaction:        'طلبات الرضا حسب القسم',
    chartComplaint:           'الشكاوى حسب القسم',
    chartStaffType:           'الطلبات حسب نوع الموظف',
    staffAcademic:            'أكاديمي',
    staffAdmin:               'إداري',
    staffWorker:              'عامل',
    staffStudent:             'طالب',
    staffOther:               'أخرى',
    publicApply:              'تقديم طلب عام',
    publicTrack:              'تتبع الطلب',
    publicTrackSub:           'يمكنك الاستعلام عن حالة طلبك برقم التتبع وعنوان البريد الإلكتروني.',
    personalInfo:             'المعلومات الشخصية',
    firstName:                'الاسم الأول',
    lastName:                 'اسم العائلة',
    idNumber:                 'رقم الهوية',
    jobTitle:                 'المسمى الوظيفي',
    address:                  'العنوان',
    hideInfo:                 'إخفاء معلوماتي الشخصية',
    hideInfoSub:              'لا يمكن للموظفين رؤية هويتي',
    required:                 'مطلوب',
    optional:                 'اختياري',
    nextStep:                 'الخطوة التالية',
    prevStep:                 'العودة إلى النموذج',
    finishApply:              'إنهاء الطلب',
    cancelApply:              'إلغاء والخروج',
    termsTitle:               'الشروط والأحكام',
    termsAccept:              'قرأت وأوافق.',
    summary:                  'معاينة الملخص',
    trackButton:              'بحث',
    trackResult:              'نتيجة الاستعلام',
    newQuery:                 'استعلام جديد',
    noDeptAssigned:           'لم يتم تعيين قسم',
    timelineTitle:            'سجل المعالجة',
    trackDescription:         'تتبع الحالة الحالية لطلبك برقم التتبع وعنوان البريد الإلكتروني.',
    applySuccess:             'تم استلام طلبك بنجاح!',
    trackingNo:               'رقم التتبع الخاص بك',
    trackNow:                 'تتبع طلبي',
    relevantDept:             'القسم المعني (المؤسسة المستهدفة)',
    selectDept:               'يرجى اختيار القسم...',
    visitorAction:            'المتابعة كزائر (بدون حساب)',
    newApplication:           'طلب جديد',
    trackApplication:         'تتبع الطلب',
    forgotPassword:           'نسيت كلمة المرور؟',
    copyright:                '© 2026 مركز اتصالات ريمر. جميع الحقوق محفوظة.',
  },

  // ─── Español ──────────────────────────────────────────────────────────────
  es: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'Iniciar sesión',
    register:                 'Registrarse',
    logout:                   'Cerrar sesión',
    email:                    'Correo electrónico',
    password:                 'Contraseña',
    passwordConfirm:          'Confirmar contraseña',
    fullName:                 'Nombre completo',
    submit:                   'Enviar',
    sending:                  'Enviando…',
    loading:                  'Cargando…',
    saving:                   'Guardando…',
    cancel:                   'Cancelar',
    back:                     '← Atrás',
    newTicket:                'Nueva solicitud',
    myTickets:                'Mis solicitudes',
    ticketNo:                 'Nº de solicitud',
    category:                 'Categoría',
    subject:                  'Asunto',
    status:                   'Estado',
    date:                     'Fecha de solicitud',
    detail:                   'Ver detalle',
    ticketDetail:             'Detalle de solicitud',
    timeline:                 'Línea de tiempo',
    updateStatus:             'Actualizar estado',
    note:                     'Añadir nota (opcional)…',
    save:                     'Guardar',
    noTickets:                'Aún no ha enviado ninguna solicitud.',
    titleLabel:               'Asunto',
    titlePlaceholder:         'Título breve',
    msgLabel:                 'Mensaje',
    msgPlaceholder:           'Describa su solicitud en detalle…',
    adminBadge:               'Administrador',
    created:                  'Creado',
    statusChanged:            'Estado cambiado',
    statusOpen:               'Recibido',
    statusInProgress:         'En proceso',
    statusClosed:             'Resuelto',
    statusSubmitted:          'Enviado',
    statusReviewing:          'En revisión',
    statusWaitingDepartment:  'En el departamento',
    statusAnswered:           'Respondido',
    cat0:                     'Queja',
    cat1:                     'Sugerencia',
    cat2:                     'Solicitud de soporte',
    cat3:                     'Agradecimiento',
    cat4:                     'Pregunta',
    cat5:                     'Solicitud de información',
    adminHint:                'Administrador:',
    waiting:                  'Por favor espere…',
    allRequests:              'Todas las solicitudes',
    total:                    'total',
    filterAll:                'Todo',
    welcomeBack:              '¡Bienvenido de nuevo!',
    loginDesc:                'Inicie sesión en su cuenta',
    noAccount:                '¿No tiene una cuenta?',
    invalidCreds:             'Credenciales inválidas',
    connError:                'Error de conexión',
    Complaint:                'Queja',
    Suggestion:               'Sugerencia',
    SupportRequest:           'Solicitud de soporte',
    Request:                  'Solicitud de soporte',
    Appreciation:             'Agradecimiento',
    Question:                 'Pregunta',
    InfoRequest:              'Solicitud de información',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    myTicketsSub:             'Gestione y realice un seguimiento de sus solicitudes de servicio.',
    searchPlaceholder:        'Buscar por número de referencia o título...',
    chartCategory:            'Distribución por categorías',
    chartTrend:               'Tendencia mensual de estado (últimos 6 meses)',
    chartDept:                'Clasificación de departamentos',
    chartAging:               'Análisis de antigüedad',
    chartPerformance:         'Análisis de rendimiento de la unidad',
    statRate:                 'Tasa de resolución',
    statUnansweredCount:      'Sin respuesta',
    statResolved:             'Resuelto',
    statPending:              'En proceso',
    statWaiting:              'En espera',
    statUnanswered:           'Sin respuesta',
    statTotal:                'Total',
    filterMonth:              'Este mes',
    filterYear:               'Este año',
    filterCustom:             'Personalizado',
    apply:                    'Aplicar',
    exportPdf:                'EXPORTAR INFORME PDF',
    aging45:                  '45+ DÍAS',
    aging60:                  '60+ DÍAS',
    aging90:                  '90+ DÍAS',
    aging180:                 '180+ DÍAS',
    noDeptData:               'No hay datos de departamento',
    pdfReportTitle:           'Informe de rendimiento analítico',
    pdfOfficialDoc:           'Documento de análisis oficial',
    pdfGeneratedBy:           'Este informe fue generado automáticamente por RİMER.',
    pdfAllTime:               'Todo el tiempo',
    catInfo:                  'Información',
    catThanks:                'Agradecimiento',
    perfScore:                'Puntuación de rendimiento',
    perfOverdue:              'Vencido',
    perfCritical:             'Crítico',
    perfTransfer:             'Tasa de transferencia',
    perfInProgress:           'En progreso',
    perfExcellent:            'Excelente',
    perfGood:                 'Bueno',
    perfWarning:              'Advertencia',
    perfCriticalLabel:        'Crítico',
    perfResRate:              'Tasa de resolución',
    perfOverdueRate:          'Tasa de vencimiento',
    chartSatisfaction:        'Solicitudes de satisfacción por departamento',
    chartComplaint:           'Quejas por departamento',
    chartStaffType:           'Solicitudes por tipo de personal',
    staffAcademic:            'Académico',
    staffAdmin:               'Administrativo',
    staffWorker:              'Trabajador',
    staffStudent:             'Estudiante',
    staffOther:               'Otro',
    publicApply:              'Solicitud pública',
    publicTrack:              'Seguimiento de solicitud',
    publicTrackSub:           'Puede consultar el estado de su solicitud con el código de seguimiento y correo electrónico proporcionados.',
    personalInfo:             'Información personal',
    firstName:                'NOMBRE',
    lastName:                 'APELLIDO',
    idNumber:                 'NÚMERO DE ID',
    jobTitle:                 'CARGO',
    address:                  'DIRECCIÓN',
    hideInfo:                 'Ocultar mi información personal',
    hideInfoSub:              'El personal no puede ver mi identidad',
    required:                 'OBLIGATORIO',
    optional:                 'OPCIONAL',
    nextStep:                 'SIGUIENTE PASO',
    prevStep:                 'VOLVER AL FORMULARIO',
    finishApply:              'FINALIZAR SOLICITUD',
    cancelApply:              'CANCELAR Y SALIR',
    termsTitle:               'TÉRMINOS Y CONDICIONES',
    termsAccept:              'He leído y acepto.',
    summary:                  'VISTA PREVIA RESUMIDA',
    trackButton:              'BUSCAR',
    trackResult:              'Resultado de consulta',
    newQuery:                 'Nueva consulta',
    noDeptAssigned:           'Sin unidad asignada',
    timelineTitle:            'Historial de procesamiento',
    trackDescription:         'Siga el estado actual de su solicitud con su número de seguimiento y correo electrónico.',
    applySuccess:             '¡Su solicitud ha sido recibida con éxito!',
    trackingNo:               'Su número de seguimiento',
    trackNow:                 'RASTREAR MI SOLICITUD',
    relevantDept:             'UNIDAD RELEVANTE (INSTITUCIÓN OBJETIVO)',
    selectDept:               'Por favor seleccione una unidad...',
    visitorAction:            'Continuar como visitante (sin cuenta)',
    newApplication:           'Nueva solicitud',
    trackApplication:         'Rastrear solicitud',
    forgotPassword:           '¿Olvidó su contraseña?',
    copyright:                '© 2026 Centro de Comunicaciones Rimer. Todos los derechos reservados.',
  },

  // ─── Deutsch ──────────────────────────────────────────────────────────────
  de: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'Anmelden',
    register:                 'Registrieren',
    logout:                   'Abmelden',
    email:                    'E-Mail',
    password:                 'Passwort',
    passwordConfirm:          'Passwort bestätigen',
    fullName:                 'Vollständiger Name',
    submit:                   'Absenden',
    sending:                  'Wird gesendet…',
    loading:                  'Wird geladen…',
    saving:                   'Wird gespeichert…',
    cancel:                   'Abbrechen',
    back:                     '← Zurück',
    newTicket:                'Neue Anfrage',
    myTickets:                'Meine Anfragen',
    ticketNo:                 'Anfragenummer',
    category:                 'Kategorie',
    subject:                  'Betreff',
    status:                   'Status',
    date:                     'Antragsdatum',
    detail:                   'Details anzeigen',
    ticketDetail:             'Anfragedetails',
    timeline:                 'Zeitachse',
    updateStatus:             'Status aktualisieren',
    note:                     'Notiz hinzufügen (optional)…',
    save:                     'Speichern',
    noTickets:                'Sie haben noch keine Anfragen gestellt.',
    titleLabel:               'Betreff',
    titlePlaceholder:         'Kurzer Titel',
    msgLabel:                 'Nachricht',
    msgPlaceholder:           'Beschreiben Sie Ihre Anfrage im Detail…',
    adminBadge:               'Administrator',
    created:                  'Erstellt',
    statusChanged:            'Status geändert',
    statusOpen:               'Empfangen',
    statusInProgress:         'In Bearbeitung',
    statusClosed:             'Gelöst',
    statusSubmitted:          'Eingereicht',
    statusReviewing:          'In Prüfung',
    statusWaitingDepartment:  'Bei der Abteilung',
    statusAnswered:           'Beantwortet',
    cat0:                     'Beschwerde',
    cat1:                     'Vorschlag',
    cat2:                     'Support-Anfrage',
    cat3:                     'Wertschätzung',
    cat4:                     'Frage',
    cat5:                     'Informationsanfrage',
    adminHint:                'Administrator:',
    waiting:                  'Bitte warten…',
    allRequests:              'Alle Anfragen',
    total:                    'gesamt',
    filterAll:                'Alle',
    welcomeBack:              'Willkommen zurück!',
    loginDesc:                'Melden Sie sich in Ihrem Konto an',
    noAccount:                'Haben Sie kein Konto?',
    invalidCreds:             'Ungültige Anmeldedaten',
    connError:                'Verbindungsfehler',
    Complaint:                'Beschwerde',
    Suggestion:               'Vorschlag',
    SupportRequest:           'Support-Anfrage',
    Request:                  'Support-Anfrage',
    Appreciation:             'Wertschätzung',
    Question:                 'Frage',
    InfoRequest:              'Informationsanfrage',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    myTicketsSub:             'Verwalten und verfolgen Sie Ihre Serviceanfragen.',
    searchPlaceholder:        'Nach Referenznummer oder Titel suchen...',
    chartCategory:            'Kategorieverteilung',
    chartTrend:               'Monatlicher Statustrend (letzte 6 Monate)',
    chartDept:                'Abteilungsranking',
    chartAging:               'Altersanalyse',
    chartPerformance:         'Einheitsleistungsanalyse',
    statRate:                 'Lösungsrate',
    statUnansweredCount:      'Unbeantwortet',
    statResolved:             'Gelöst',
    statPending:              'In Bearbeitung',
    statWaiting:              'Wartend',
    statUnanswered:           'Unbeantwortet',
    statTotal:                'Gesamt',
    filterMonth:              'Diesen Monat',
    filterYear:               'Dieses Jahr',
    filterCustom:             'Benutzerdefiniert',
    apply:                    'Anwenden',
    exportPdf:                'PDF-BERICHT EXPORTIEREN',
    aging45:                  '45+ TAGE',
    aging60:                  '60+ TAGE',
    aging90:                  '90+ TAGE',
    aging180:                 '180+ TAGE',
    noDeptData:               'Keine Abteilungsdaten',
    pdfReportTitle:           'Analytischer Leistungsbericht',
    pdfOfficialDoc:           'Offizielles Analysedokument',
    pdfGeneratedBy:           'Dieser Bericht wurde automatisch von RİMER erstellt.',
    pdfAllTime:               'Gesamte Zeit',
    catInfo:                  'Information',
    catThanks:                'Wertschätzung',
    perfScore:                'Leistungspunktzahl',
    perfOverdue:              'Überfällig',
    perfCritical:             'Kritisch',
    perfTransfer:             'Transferrate',
    perfInProgress:           'In Bearbeitung',
    perfExcellent:            'Ausgezeichnet',
    perfGood:                 'Gut',
    perfWarning:              'Warnung',
    perfCriticalLabel:        'Kritisch',
    perfResRate:              'Lösungsrate',
    perfOverdueRate:          'Überfälligkeitsrate',
    chartSatisfaction:        'Zufriedenheitsanfragen nach Abteilung',
    chartComplaint:           'Beschwerden nach Abteilung',
    chartStaffType:           'Anfragen nach Personaltyp',
    staffAcademic:            'Akademisch',
    staffAdmin:               'Verwaltung',
    staffWorker:              'Arbeiter',
    staffStudent:             'Student',
    staffOther:               'Sonstige',
    publicApply:              'Öffentlicher Antrag',
    publicTrack:              'Antragsverfolgung',
    publicTrackSub:           'Sie können den Status Ihres Antrags mit der bereitgestellten Tracking-Nummer und E-Mail-Adresse abfragen.',
    personalInfo:             'Persönliche Informationen',
    firstName:                'VORNAME',
    lastName:                 'NACHNAME',
    idNumber:                 'AUSWEISNUMMER',
    jobTitle:                 'BERUFSBEZEICHNUNG',
    address:                  'ADRESSE',
    hideInfo:                 'Meine persönlichen Daten ausblenden',
    hideInfoSub:              'Mitarbeiter können meine Identität nicht sehen',
    required:                 'ERFORDERLICH',
    optional:                 'OPTIONAL',
    nextStep:                 'NÄCHSTER SCHRITT',
    prevStep:                 'ZURÜCK ZUM FORMULAR',
    finishApply:              'ANTRAG ABSCHLIESSEN',
    cancelApply:              'ABBRECHEN UND VERLASSEN',
    termsTitle:               'ALLGEMEINE GESCHÄFTSBEDINGUNGEN',
    termsAccept:              'Ich habe gelesen und stimme zu.',
    summary:                  'ZUSAMMENFASSUNGSVORSCHAU',
    trackButton:              'SUCHEN',
    trackResult:              'Abfrageergebnis',
    newQuery:                 'Neue Abfrage',
    noDeptAssigned:           'Keine Einheit zugewiesen',
    timelineTitle:            'Bearbeitungshistorie',
    trackDescription:         'Verfolgen Sie den aktuellen Status Ihres Antrags mit Ihrer Tracking-Nummer und E-Mail-Adresse.',
    applySuccess:             'Ihr Antrag wurde erfolgreich eingegangen!',
    trackingNo:               'Ihre Tracking-Nummer',
    trackNow:                 'MEINEN ANTRAG VERFOLGEN',
    relevantDept:             'ZUSTÄNDIGE EINHEIT (ZIELINSTITUTION)',
    selectDept:               'Bitte wählen Sie eine Einheit...',
    visitorAction:            'Als Besucher fortfahren (ohne Konto)',
    newApplication:           'Neuer Antrag',
    trackApplication:         'Antrag verfolgen',
    forgotPassword:           'Passwort vergessen?',
    copyright:                '© 2026 Rimer Kommunikationszentrum. Alle Rechte vorbehalten.',
  },

  // ─── 日本語 (Japanese) ─────────────────────────────────────────────────────
  ja: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'ログイン',
    register:                 '登録',
    logout:                   'ログアウト',
    email:                    'メールアドレス',
    password:                 'パスワード',
    passwordConfirm:          'パスワード確認',
    fullName:                 'フルネーム',
    submit:                   '送信',
    sending:                  '送信中…',
    loading:                  '読み込み中…',
    saving:                   '保存中…',
    cancel:                   'キャンセル',
    back:                     '← 戻る',
    newTicket:                '新規リクエスト',
    myTickets:                'マイリクエスト',
    ticketNo:                 'リクエスト番号',
    category:                 'カテゴリー',
    subject:                  '件名',
    status:                   'ステータス',
    date:                     '申請日',
    detail:                   '詳細を見る',
    ticketDetail:             'リクエスト詳細',
    timeline:                 'タイムライン',
    updateStatus:             'ステータスを更新',
    note:                     'メモを追加（任意）…',
    save:                     '保存',
    noTickets:                'リクエストはまだありません。',
    titleLabel:               '件名',
    titlePlaceholder:         '短いタイトル',
    msgLabel:                 'メッセージ',
    msgPlaceholder:           'リクエストを詳細に記述してください…',
    adminBadge:               '管理者',
    created:                  '作成済み',
    statusChanged:            'ステータス変更済み',
    statusOpen:               '受信済み',
    statusInProgress:         '処理中',
    statusClosed:             '解決済み',
    statusSubmitted:          '提出済み',
    statusReviewing:          '審査中',
    statusWaitingDepartment:  '該当部門にて',
    statusAnswered:           '回答済み',
    cat0:                     '苦情',
    cat1:                     '提案',
    cat2:                     'サポートリクエスト',
    cat3:                     '感謝',
    cat4:                     '質問',
    cat5:                     '情報リクエスト',
    adminHint:                '管理者:',
    waiting:                  'お待ちください…',
    allRequests:              'すべてのリクエスト',
    total:                    '合計',
    filterAll:                'すべて',
    welcomeBack:              'お帰りなさい！',
    loginDesc:                'アカウントにログインする',
    noAccount:                'アカウントをお持ちでないですか？',
    invalidCreds:             '無効な認証情報です',
    connError:                '接続エラー',
    Complaint:                '苦情',
    Suggestion:               '提案',
    SupportRequest:           'サポートリクエスト',
    Request:                  'サポートリクエスト',
    Appreciation:             '感謝',
    Question:                 '質問',
    InfoRequest:              '情報リクエスト',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    myTicketsSub:             'サービスリクエストを管理し、追跡します。',
    searchPlaceholder:        '参照番号またはタイトルで検索...',
    chartCategory:            'カテゴリーの分布',
    chartTrend:               '月別ステータス傾向 (過去6ヶ月)',
    chartDept:                '部門ランキング',
    chartAging:               '期間分析',
    chartPerformance:         '部門パフォーマンス分析',
    statRate:                 '解決率',
    statUnansweredCount:      '未回答',
    statResolved:             '解決済み',
    statPending:              '処理中',
    statWaiting:              '待機中',
    statUnanswered:           '未回答',
    statTotal:                '合計',
    filterMonth:              '今月',
    filterYear:               '今年',
    filterCustom:             'カスタム',
    apply:                    '適用',
    exportPdf:                'PDFレポートを出力',
    aging45:                  '45日以上',
    aging60:                  '60日以上',
    aging90:                  '90日以上',
    aging180:                 '180日以上',
    noDeptData:               '部門データなし',
    pdfReportTitle:           '分析パフォーマンスレポート',
    pdfOfficialDoc:           '公式分析文書',
    pdfGeneratedBy:           'このレポートはRİMERによって自動生成されました。',
    pdfAllTime:               '全期間',
    catInfo:                  '情報',
    catThanks:                '感謝',
    perfScore:                'パフォーマンススコア',
    perfOverdue:              '期限切れ',
    perfCritical:             '重大',
    perfTransfer:             '転送率',
    perfInProgress:           '進行中',
    perfExcellent:            '優秀',
    perfGood:                 '良好',
    perfWarning:              '警告',
    perfCriticalLabel:        '重大',
    perfResRate:              '解決率',
    perfOverdueRate:          '遅延率',
    chartSatisfaction:        '部門別満足度リクエスト',
    chartComplaint:           '部門別苦情',
    chartStaffType:           'スタッフタイプ別リクエスト',
    staffAcademic:            '学術',
    staffAdmin:               '管理',
    staffWorker:              '労働者',
    staffStudent:             '学生',
    staffOther:               'その他',
    publicApply:              '一般申請',
    publicTrack:              '申請の追跡',
    publicTrackSub:           '追跡コードとメールアドレスを使用して申請状況を確認できます。',
    personalInfo:             '個人情報',
    firstName:                '名前',
    lastName:                 '姓',
    idNumber:                 '身分証明書番号',
    jobTitle:                 '役職',
    address:                  '住所',
    hideInfo:                 '個人情報を隠す',
    hideInfoSub:              'スタッフは私の身元を確認できません',
    required:                 '必須',
    optional:                 '任意',
    nextStep:                 '次のステップへ',
    prevStep:                 'フォームに戻る',
    finishApply:              '申請を完了する',
    cancelApply:              'キャンセルして終了',
    termsTitle:               '利用規約',
    termsAccept:              '読み、同意しました。',
    summary:                  'サマリーのプレビュー',
    trackButton:              '検索',
    trackResult:              '検索結果',
    newQuery:                 '新規検索',
    noDeptAssigned:           '担当部署なし',
    timelineTitle:            '処理履歴',
    trackDescription:         '追跡番号とメールアドレスで申請の最新状況を確認してください。',
    applySuccess:             '申請が正常に受け付けられました！',
    trackingNo:               '追跡番号',
    trackNow:                 '申請を追跡する',
    relevantDept:             '関連部署（対象機関）',
    selectDept:               '部署を選択してください...',
    visitorAction:            '訪問者として続ける（アカウントなし）',
    newApplication:           '新規申請',
    trackApplication:         '申請追跡',
    forgotPassword:           'パスワードをお忘れですか？',
    copyright:                '© 2026 Rimer 通信センター。全著作権所有。',
  },

  // ─── اردو (Urdu) ─────────────────────────────────────────────────────────
  ur: {
    ...BASE,
    appName:                  'Rimer',
    login:                    'لاگ ان',
    register:                 'رجسٹر',
    logout:                   'لاگ آؤٹ',
    email:                    'ای میل',
    password:                 'پاس ورڈ',
    passwordConfirm:          'پاس ورڈ کی تصدیق',
    fullName:                 'پورا نام',
    submit:                   'جمع کروائیں',
    sending:                  'بھیج رہا ہے…',
    loading:                  'لوڈ ہو رہا ہے…',
    saving:                   'محفوظ ہو رہا ہے…',
    cancel:                   'منسوخ کریں',
    back:                     '← واپس',
    newTicket:                'نئی درخواست',
    myTickets:                'میری درخواستیں',
    ticketNo:                 'درخواست نمبر',
    category:                 'زمرہ',
    subject:                  'موضوع',
    status:                   'حالت',
    date:                     'تاریخ',
    detail:                   'تفصیل دیکھیں',
    ticketDetail:             'درخواست کی تفصیل',
    timeline:                 'ٹائم لائن',
    updateStatus:             'حالت اپ ڈیٹ کریں',
    note:                     'نوٹ شامل کریں (اختیاری)…',
    save:                     'محفوظ کریں',
    noTickets:                'ابھی تک کوئی درخواست جمع نہیں کی گئی۔',
    titleLabel:               'موضوع',
    titlePlaceholder:         'مختصر عنوان',
    msgLabel:                 'پیغام',
    msgPlaceholder:           'اپنی درخواست کی تفصیل بیان کریں…',
    adminBadge:               'ایڈمن',
    created:                  'تخلیق کیا گیا',
    statusChanged:            'حالت تبدیل ہو گئی',
    statusOpen:               'موصول ہوا',
    statusInProgress:         'جاری ہے',
    statusClosed:             'حل ہو گیا',
    statusSubmitted:          'جمع کرایا گیا',
    statusReviewing:          'زیر غور',
    statusWaitingDepartment:  'محکمہ میں',
    statusAnswered:           'جواب دیا گیا',
    cat0:                     'شکایت',
    cat1:                     'تجویز',
    cat2:                     'مدد کی درخواست',
    cat3:                     'تعریف',
    cat4:                     'سوال',
    cat5:                     'معلومات کی درخواست',
    adminHint:                'ایڈمن:',
    waiting:                  'براہ کرم انتظار کریں…',
    allRequests:              'تمام درخواستیں',
    total:                    'کل',
    filterAll:                'سب',
    welcomeBack:              'خوش آمدید!',
    loginDesc:                'اپنے اکاؤنٹ میں لاگ ان کریں',
    noAccount:                'کیا آپ کا اکاؤنٹ نہیں ہے؟',
    invalidCreds:             'غلط معلومات',
    connError:                'رابطے کی خرابی',
    Complaint:                'شکایت',
    Suggestion:               'تجویز',
    SupportRequest:           'مدد کی درخواست',
    Request:                  'مدد کی درخواست',
    Appreciation:             'تعریف',
    Question:                 'سوال',
    InfoRequest:              'معلومات کی درخواست',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    langUr:                   'اردو',
    langKo:                   '한국어',
    myTicketsSub:             'اپنی سروس کی درخواستوں کا انتظام کریں۔',
    searchPlaceholder:        'حوالہ نمبر یا عنوان سے تلاش کریں...',
    chartCategory:            'زمرہ کی تقسیم',
    chartTrend:               'ماہانہ رجحان',
    chartDept:                'محکمہ کی درجہ بندی',
    chartAging:               'عمر کا تجزیہ',
    chartPerformance:         'یونٹ کی کارکردگی',
    statRate:                 'حل کی شرح',
    statUnansweredCount:      'بغیر جواب',
    statResolved:             'حل ہو گیا',
    statPending:              'جاری ہے',
    statWaiting:              'انتظار میں',
    statUnanswered:           'بغیر جواب',
    statTotal:                'کل',
    filterMonth:              'اس ماہ',
    filterYear:               'اس سال',
    filterCustom:             'اپنی مرضی کے مطابق',
    apply:                    'لاگو کریں',
    exportPdf:                'پی ڈی ایف رپورٹ',
    aging45:                  '45+ دن',
    aging60:                  '60+ دن',
    aging90:                  '90+ دن',
    aging180:                 '180+ دن',
    noDeptData:               'کوئی ڈیٹا نہیں',
    pdfReportTitle:           'کارکردگی کی رپورٹ',
    pdfOfficialDoc:           'سرکاری دستاویز',
    pdfGeneratedBy:           'یہ رپورٹ خود بخود تیار کی گئی ہے۔',
    pdfAllTime:               'تمام وقت',
    catInfo:                  'معلومات',
    catThanks:                'تعریف',
    perfScore:                'کارکردگی کا سکور',
    perfOverdue:              'زائد المیعاد',
    perfCritical:             'انتہائی اہم',
    perfTransfer:             'منتقلی کی شرح',
    perfInProgress:           'جاری ہے',
    perfExcellent:            'بہترین',
    perfGood:                 'اچھا',
    perfWarning:              'انتباہ',
    perfCriticalLabel:        'انتہائی اہم',
    perfResRate:              'حل کی شرح',
    perfOverdueRate:          'تاخیر کی شرح',
    chartSatisfaction:        'اطمینان کی درخواستیں',
    chartComplaint:           'شکایات',
    chartStaffType:           'عملہ کی قسم',
    staffAcademic:            'تعلیمی',
    staffAdmin:               'انتظامی',
    staffWorker:              'ورکر',
    staffStudent:             'طالب علم',
    staffOther:               'دیگر',
    publicApply:              'عوامی درخواست',
    publicTrack:              'درخواست کی ٹریکنگ',
    publicTrackSub:           'اپنی درخواست کی حالت چیک کریں۔',
    personalInfo:             'ذاتی معلومات',
    firstName:                'پہلا نام',
    lastName:                 'آخری نام',
    idNumber:                 'شناختی نمبر',
    jobTitle:                 'عہدہ',
    address:                  'پتہ',
    hideInfo:                 'میری ذاتی معلومات چھپائیں',
    hideInfoSub:              'عملہ میری شناخت نہیں دیکھ سکتا',
    required:                 'ضروری',
    optional:                 'اختیاری',
    nextStep:                 'اگلا قدم',
    prevStep:                 'فارم پر واپس',
    finishApply:              'درخواست مکمل کریں',
    cancelApply:              'منسوخ کریں اور چھوڑیں',
    termsTitle:               'شرائط و ضوابط',
    termsAccept:              'میں نے پڑھ لیا ہے اور اتفاق کرتا ہوں۔',
    summary:                  'خلاصہ',
    trackButton:              'ٹریک',
    trackResult:              'نتیجہ',
    newQuery:                 'نئی تلاش',
    noDeptAssigned:           'کوئی محکمہ نہیں',
    timelineTitle:            'تاریخ',
    trackDescription:         'اپنی درخواست کو ٹریک کریں۔',
    applySuccess:             'آپ کی درخواست موصول ہو گئی ہے!',
    trackingNo:               'آپ کا ٹریکنگ نمبر',
    trackNow:                 'میری درخواست کو ٹریک کریں',
    relevantDept:             'متعلقہ محکمہ',
    selectDept:               'محکمہ منتخب کریں...',
    visitorAction:            'وزیٹر کے طور پر جاری رکھیں',
    newApplication:           'نئی درخواست',
    trackApplication:         'درخواست ٹریک کریں',
    forgotPassword:           'پاس ورڈ بھول گئے؟',
    copyright:                '© 2026 ریمر کمیونیکیشن سنٹر۔ جملہ حقوق محفوظ ہیں۔',
  },

  // ─── 한국어 (Korean) ────────────────────────────────────────────────────────
  ko: {
    ...BASE,
    appName:                  'Rimer',
    login:                    '로그인',
    register:                 '등록',
    logout:                   '로그아웃',
    email:                    '이메일',
    password:                 '비밀번호',
    passwordConfirm:          '비밀번호 확인',
    fullName:                 '성명',
    submit:                   '제출',
    sending:                  '전송 중…',
    loading:                  '로딩 중…',
    saving:                   '저장 중…',
    cancel:                   '취소',
    back:                     '← 뒤로',
    newTicket:                '새 요청',
    myTickets:                '내 요청',
    ticketNo:                 '요청 번호',
    category:                 '카테고리',
    subject:                  '제목',
    status:                   '상태',
    date:                     '날짜',
    detail:                   '자세히 보기',
    ticketDetail:             '요청 세부 정보',
    timeline:                 '타임라인',
    updateStatus:             '상태 업데이트',
    note:                     '메모 추가(선택 사항)…',
    save:                     '저장',
    noTickets:                '제출된 요청이 없습니다.',
    titleLabel:               '제목',
    titlePlaceholder:         '짧은 제목',
    msgLabel:                 '메시지',
    msgPlaceholder:           '요청 사항을 자세히 설명해주세요…',
    adminBadge:               '관리자',
    created:                  '생성됨',
    statusChanged:            '상태 변경됨',
    statusOpen:               '접수됨',
    statusInProgress:         '진행 중',
    statusClosed:             '해결됨',
    statusSubmitted:          '제출됨',
    statusReviewing:          '검토 중',
    statusWaitingDepartment:  '부서 대기 중',
    statusAnswered:           '답변됨',
    cat0:                     '불만 사항',
    cat1:                     '제안',
    cat2:                     '지원 요청',
    cat3:                     '감사',
    cat4:                     '질문',
    cat5:                     '정보 요청',
    adminHint:                '관리자:',
    waiting:                  '잠시 기다려주세요…',
    allRequests:              '모든 요청',
    total:                    '총',
    filterAll:                '전체',
    welcomeBack:              '환영합니다!',
    loginDesc:                '계정에 로그인하세요',
    noAccount:                '계정이 없으신가요?',
    invalidCreds:             '잘못된 자격 증명',
    connError:                '연결 오류',
    Complaint:                '불만 사항',
    Suggestion:               '제안',
    SupportRequest:           '지원 요청',
    Request:                  '지원 요청',
    Appreciation:             '감사',
    Question:                 '질문',
    InfoRequest:              '정보 요청',
    langTr:                   'Türkçe',
    langEn:                   'English',
    langZh:                   '中文',
    langAz:                   'Azərbaycanca',
    langRu:                   'Русский',
    langKk:                   'Қазақша',
    langAr:                   'العربية',
    langEs:                   'Español',
    langDe:                   'Deutsch',
    langJa:                   '日本語',
    langUr:                   'اردو',
    langKo:                   '한국어',
    myTicketsSub:             '서비스 요청을 관리하고 추적하세요.',
    searchPlaceholder:        '참조 번호 또는 제목으로 검색...',
    chartCategory:            '카테고리 분포',
    chartTrend:               '월별 상태 동향',
    chartDept:                '부서 순위',
    chartAging:               '경과 시간 분석',
    chartPerformance:         '부서 성과 분석',
    statRate:                 '해결률',
    statUnansweredCount:      '미응답',
    statResolved:             '해결됨',
    statPending:              '진행 중',
    statWaiting:              '대기 중',
    statUnanswered:           '미응답',
    statTotal:                '총계',
    filterMonth:              '이번 달',
    filterYear:               '올해',
    filterCustom:             '사용자 지정',
    apply:                    '적용',
    exportPdf:                'PDF 보고서 내보내기',
    aging45:                  '45일 이상',
    aging60:                  '60일 이상',
    aging90:                  '90일 이상',
    aging180:                 '180일 이상',
    noDeptData:               '부서 데이터 없음',
    pdfReportTitle:           '분석 성과 보고서',
    pdfOfficialDoc:           '공식 분석 문서',
    pdfGeneratedBy:           '이 보고서는 시스템에서 자동으로 생성되었습니다.',
    pdfAllTime:               '전체 기간',
    catInfo:                  '정보',
    catThanks:                '감사',
    perfScore:                '성과 점수',
    perfOverdue:              '기한 초과',
    perfCritical:             '위험',
    perfTransfer:             '이전율',
    perfInProgress:           '진행 중',
    perfExcellent:            '우수',
    perfGood:                 '양호',
    perfWarning:              '경고',
    perfCriticalLabel:        '위험',
    perfResRate:              '해결률',
    perfOverdueRate:          '지연율',
    chartSatisfaction:        '부서별 만족도',
    chartComplaint:           '부서별 불만 사항',
    chartStaffType:           '직원 유형별 신청',
    staffAcademic:            '학술',
    staffAdmin:               '행정',
    staffWorker:              '근로자',
    staffStudent:             '학생',
    staffOther:               '기타',
    publicApply:              '공개 신청',
    publicTrack:              '신청 추적',
    publicTrackSub:           '제공된 추적 번호와 이메일로 신청 상태를 확인하세요.',
    personalInfo:             '개인 정보',
    firstName:                '이름',
    lastName:                 '성',
    idNumber:                 '신분증 번호',
    jobTitle:                 '직함',
    address:                  '주소',
    hideInfo:                 '내 개인 정보 숨기기',
    hideInfoSub:              '직원은 내 신원을 볼 수 없습니다',
    required:                 '필수',
    optional:                 '선택',
    nextStep:                 '다음 단계',
    prevStep:                 '양식으로 돌아가기',
    finishApply:              '신청 완료',
    cancelApply:              '취소 및 종료',
    termsTitle:               '이용 약관',
    termsAccept:              '읽었으며 동의합니다.',
    summary:                  '요약 미리보기',
    trackButton:              '추적',
    trackResult:              '조회 결과',
    newQuery:                 '새 조회',
    noDeptAssigned:           '할당된 부서 없음',
    timelineTitle:            '처리 내역',
    trackDescription:         '추적 번호와 이메일 주소로 신청 상태를 확인하세요.',
    applySuccess:             '신청이 성공적으로 접수되었습니다!',
    trackingNo:               '추적 번호',
    trackNow:                 '내 신청 추적하기',
    relevantDept:             '관련 부서',
    selectDept:               '부서를 선택하세요...',
    visitorAction:            '방문자로 계속 (계정 불필요)',
    newApplication:           '새 신청',
    trackApplication:         '신청 추적',
    forgotPassword:           '비밀번호를 잊으셨나요?',
    copyright:                '© 2026 Rimer Communication Center. All rights reserved.',
  },
}

const LANG_KEY  = 'rimer_lang'
const THEME_KEY = 'rimer_theme'

// ── i18n store ────────────────────────────────────────────────────────────────
export const i18n = reactive({
  lang: localStorage.getItem(LANG_KEY) || 'tr',
  get t() { return dict[this.lang] ?? dict['tr'] },
  set(l) {
    this.lang = l
    localStorage.setItem(LANG_KEY, l)
    // RTL support for Arabic
    document.documentElement.setAttribute('dir', l === 'ar' ? 'rtl' : 'ltr')
  },
})

// Apply RTL on init if needed
if (i18n.lang === 'ar') {
  document.documentElement.setAttribute('dir', 'rtl')
}

// ── Theme store ───────────────────────────────────────────────────────────────
export const theme = reactive({
  dark: localStorage.getItem(THEME_KEY) !== 'light',
  init() {
    document.documentElement.classList.toggle('dark', this.dark)
    document.documentElement.classList.toggle('light', !this.dark)
  },
  toggle() {
    this.dark = !this.dark
    localStorage.setItem(THEME_KEY, this.dark ? 'dark' : 'light')
    document.documentElement.classList.toggle('dark', this.dark)
    document.documentElement.classList.toggle('light', !this.dark)
  },
})
